package com.theron.wallet.enums;

public enum AuditAction {
    LOGIN,
    LOGOUT,
    PASSWORD_CHANGED,
    USER_CREATED,
    USER_DISABLED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    ROLE_CHANGED,
    PIX_KEY_CREATED,
    PIX_KEY_REMOVED,
    TRANSFER_CREATED,
    TRANSFER_APPROVED,
    TRANSFER_REJECTED,
    BENEFICIARY_CREATED,
    BENEFICIARY_UPDATED,
    BENEFICIARY_DELETED,
    LIMIT_CHANGED
}
