package com.theron.wallet.service.impl;

import com.theron.wallet.dto.asaas.AsaasPixTransactionResponse;
import com.theron.wallet.dto.asaas.AsaasTransferResponse;
import com.theron.wallet.dto.asaas.AsaasWebhookPayload;
import com.theron.wallet.entity.PixKey;
import com.theron.wallet.entity.Subaccount;
import com.theron.wallet.enums.PixKeyStatus;
import com.theron.wallet.integration.AsaasPaymentClient;
import com.theron.wallet.integration.AsaasTransferClient;
import com.theron.wallet.repository.PixKeyRepository;
import com.theron.wallet.repository.SubaccountRepository;
import com.theron.wallet.security.AsaasApiKeyResolver;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.stereotype.Service;

import java.util.Map;

/**
 * Resolves the Theron subaccount that received an inbound Pix transaction.
 *
 * PAYMENT_RECEIVED webhooks can arrive with the platform/root Asaas account
 * even when the Pix destination is one of our linked subaccounts. In that
 * situation the webhook account.id alone is not enough to identify the wallet.
 * We therefore inspect the Pix transaction and, when possible, its originating
 * transfer, then match the destination Pix key against our own PixKey registry.
 */
@Slf4j
@Service
@RequiredArgsConstructor
public class InboundPixDestinationResolver {

    private final AsaasPaymentClient asaasPaymentClient;
    private final AsaasTransferClient asaasTransferClient;
    private final AsaasApiKeyResolver asaasApiKeyResolver;
    private final PixKeyRepository pixKeyRepository;
    private final SubaccountRepository subaccountRepository;

    public Subaccount resolve(AsaasWebhookPayload payload) {
        if (payload == null || payload.getPayment() == null) {
            return null;
        }

        String pixTransactionId = extractPixTransactionId(payload.getPayment().getPixTransaction());
        if (pixTransactionId == null || pixTransactionId.isBlank()) {
            log.warn("Inbound Pix payment has no pixTransaction id: paymentId={}",
                    payload.getPayment().getId());
            return null;
        }

        String apiKey = asaasApiKeyResolver.resolveForOutbound(null);
        AsaasPixTransactionResponse pixTransaction;
        try {
            pixTransaction = asaasPaymentClient.retrievePixTransaction(apiKey, pixTransactionId);
        } catch (RuntimeException ex) {
            log.warn("Could not retrieve Asaas Pix transaction for inbound payment: pixTransactionId={}",
                    pixTransactionId, ex);
            return null;
        }

        if (pixTransaction == null) {
            log.warn("Asaas returned an empty Pix transaction: pixTransactionId={}", pixTransactionId);
            return null;
        }

        String transferId = pixTransaction.getTransferId();
        String transactionAddressKey = pixTransaction.getAddressKey();
        String externalAddressKey = pixTransaction.getExternalAccount() != null
                ? pixTransaction.getExternalAccount().getAddressKey()
                : null;

        log.info(
                "Inbound Pix transaction details: pixTransactionId={}, status={}, transferId={}, addressKey={}, externalAccountAddressKey={}",
                pixTransactionId,
                pixTransaction.getStatus(),
                transferId,
                transactionAddressKey,
                externalAddressKey);

        // For an inbound payment generated by one of our outbound Pix transfers,
        // the originating transfer is the most deterministic source of the
        // destination key. Do this before addressKey because addressKey can refer
        // to the other side of the Pix transaction depending on the transaction type.
        if (transferId != null && !transferId.isBlank()) {
            try {
                AsaasTransferResponse transfer = asaasTransferClient.retrieveTransfer(apiKey, transferId);
                String transferAddressKey = transfer != null ? transfer.getPixAddressKey() : null;

                log.info("Inbound Pix originating transfer details: transferId={}, pixAddressKey={}, status={}",
                        transferId,
                        transferAddressKey,
                        transfer != null ? transfer.getStatus() : null);

                Subaccount resolved = findByPixKey(transferAddressKey);
                if (resolved != null) {
                    return resolved;
                }
            } catch (RuntimeException ex) {
                log.warn("Could not retrieve originating Asaas transfer for inbound Pix: transferId={}",
                        transferId, ex);
            }
        }

        // For Pix receipts that did not originate from one of our tracked
        // transfers, the transaction's own addressKey is the next candidate.
        Subaccount resolved = findByPixKey(transactionAddressKey);
        if (resolved != null) {
            return resolved;
        }

        // Keep the external account key as a final candidate. This is safe because
        // a Pix key is globally unique: if it is one of our active keys, it maps to
        // the Theron account that owns that key.
        return findByPixKey(externalAddressKey);
    }

    private Subaccount findByPixKey(String key) {
        if (key == null || key.isBlank()) {
            return null;
        }

        PixKey pixKey = pixKeyRepository.findByKeyAndStatus(key, PixKeyStatus.ACTIVE).orElse(null);
        if (pixKey == null || pixKey.getAccount() == null || pixKey.getAccount().getId() == null) {
            log.debug("No active Theron Pix key found for candidate={}", key);
            return null;
        }

        Subaccount subaccount = subaccountRepository
                .findByAccount_Id(pixKey.getAccount().getId())
                .orElse(null);

        if (subaccount != null) {
            log.info("Resolved inbound Pix destination by Pix key: key={}, subaccountId={}",
                    key, subaccount.getId());
        }
        return subaccount;
    }

    private static String extractPixTransactionId(Object pixTransaction) {
        if (pixTransaction instanceof String id && !id.isBlank()) {
            return id;
        }
        if (pixTransaction instanceof Map<?, ?> map && map.get("id") != null) {
            String id = String.valueOf(map.get("id"));
            return id.isBlank() ? null : id;
        }
        return null;
    }
}
